- hosts: webservers
  become: true
  tasks:
    - name: install prerequisites for Docker repository
      become: yes
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release

    - name: Install CRI-O
      apt:
        name:
          - cri-o
        state: present

    - name: add docker apt key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repo
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: install docker and its dependencies
      become: yes
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: start and enable docker daemon
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

    - name: start and enable containerd daemon
      become: yes
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker run hello-world
      register: docker_run
      ignore_errors: true

    - name: Display Docker verification result
      debug:
        var: docker_run.stdout

    - name: Clone the Django app from GitHub
      git:
        repo: "https://github.com/Laban254/customer-management-api"
        dest: /home/ubuntu/mydjangoapp
        force: yes