- hosts: webservers
  become: true
  tasks:
    - name: Install prerequisites for Docker repository
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
        state: present
        update_cache: yes

    - name: Create directory for Docker keyrings if not exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker's official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker-archive-keyring.gpg

    - name: Ensure Docker GPG key permissions are correct
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker and its dependencies
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start and enable Docker daemon
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable containerd daemon
      ansible.builtin.service:
        name: containerd
        state: started
        enabled: yes

    - name: Verify Docker installation
      command: docker run hello-world
      register: docker_run
      ignore_errors: true

    - name: Display Docker verification result
      debug:
        var: docker_run.stdout

    - name: Clone the Django app from GitHub
      git:
        repo: "https://github.com/Laban254/customer-management-api"
        dest: /home/ubuntu/mydjangoapp
        force: yes
